
    /*
     * To change this license header, choose License Headers in Project Properties.
     * To change this template file, choose Tools | Templates
     * and open the template in the editor.
     */
    package menubar_package;

    import javax.swing.JOptionPane;

    /**
     *
     * @author Aditya
     */
    public class Menubar extends javax.swing.JFrame {

        /**
         * Creates new form Menubar
         */
        public Menubar() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            jSeparator1 = new javax.swing.JSeparator();
            jTabbedPane1 = new javax.swing.JTabbedPane();
            jPanel2 = new javax.swing.JPanel();
            jPanel6 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jLabel3 = new javax.swing.JLabel();
            jPanel5 = new javax.swing.JPanel();
            jMenuBar1 = new javax.swing.JMenuBar();
            jMenu1 = new javax.swing.JMenu();
            jMenuItem1 = new javax.swing.JMenuItem();
            jMenuItem9 = new javax.swing.JMenuItem();
            jMenu5 = new javax.swing.JMenu();
            jMenu14 = new javax.swing.JMenu();
            jMenuItem7 = new javax.swing.JMenuItem();
            jMenuItem17 = new javax.swing.JMenuItem();
            jMenu12 = new javax.swing.JMenu();
            jMenuItem10 = new javax.swing.JMenuItem();
            jMenuItem12 = new javax.swing.JMenuItem();
            jMenu13 = new javax.swing.JMenu();
            jMenuItem13 = new javax.swing.JMenuItem();
            jMenuItem14 = new javax.swing.JMenuItem();
            jMenu11 = new javax.swing.JMenu();
            jMenuItem15 = new javax.swing.JMenuItem();
            jMenuItem16 = new javax.swing.JMenuItem();
            jMenu15 = new javax.swing.JMenu();
            jMenuItem8 = new javax.swing.JMenuItem();
            jMenuItem11 = new javax.swing.JMenuItem();
            jMenuItem18 = new javax.swing.JMenuItem();
            jMenu6 = new javax.swing.JMenu();
            jMenu16 = new javax.swing.JMenu();
            jMenuItem19 = new javax.swing.JMenuItem();
            jMenuItem20 = new javax.swing.JMenuItem();
            jMenu17 = new javax.swing.JMenu();
            jMenuItem21 = new javax.swing.JMenuItem();
            jMenuItem22 = new javax.swing.JMenuItem();
            jMenu18 = new javax.swing.JMenu();
            jMenuItem23 = new javax.swing.JMenuItem();
            jMenuItem24 = new javax.swing.JMenuItem();
            jMenu19 = new javax.swing.JMenu();
            jMenuItem25 = new javax.swing.JMenuItem();
            jMenuItem26 = new javax.swing.JMenuItem();
            jMenu20 = new javax.swing.JMenu();
            jMenuItem27 = new javax.swing.JMenuItem();
            jMenuItem28 = new javax.swing.JMenuItem();
            jMenuItem29 = new javax.swing.JMenuItem();
            jMenu7 = new javax.swing.JMenu();
            jMenu21 = new javax.swing.JMenu();
            jMenuItem30 = new javax.swing.JMenuItem();
            jMenuItem31 = new javax.swing.JMenuItem();
            jMenu22 = new javax.swing.JMenu();
            jMenuItem32 = new javax.swing.JMenuItem();
            jMenuItem33 = new javax.swing.JMenuItem();
            jMenu23 = new javax.swing.JMenu();
            jMenuItem34 = new javax.swing.JMenuItem();
            jMenuItem35 = new javax.swing.JMenuItem();
            jMenu24 = new javax.swing.JMenu();
            jMenuItem36 = new javax.swing.JMenuItem();
            jMenuItem37 = new javax.swing.JMenuItem();
            jMenu25 = new javax.swing.JMenu();
            jMenuItem38 = new javax.swing.JMenuItem();
            jMenuItem39 = new javax.swing.JMenuItem();
            jMenuItem40 = new javax.swing.JMenuItem();
            jMenu8 = new javax.swing.JMenu();
            jMenu26 = new javax.swing.JMenu();
            jMenuItem41 = new javax.swing.JMenuItem();
            jMenuItem42 = new javax.swing.JMenuItem();
            jMenu27 = new javax.swing.JMenu();
            jMenuItem43 = new javax.swing.JMenuItem();
            jMenuItem44 = new javax.swing.JMenuItem();
            jMenu28 = new javax.swing.JMenu();
            jMenuItem45 = new javax.swing.JMenuItem();
            jMenuItem46 = new javax.swing.JMenuItem();
            jMenu29 = new javax.swing.JMenu();
            jMenuItem47 = new javax.swing.JMenuItem();
            jMenuItem48 = new javax.swing.JMenuItem();
            jMenu30 = new javax.swing.JMenu();
            jMenuItem49 = new javax.swing.JMenuItem();
            jMenuItem50 = new javax.swing.JMenuItem();
            jMenuItem51 = new javax.swing.JMenuItem();
            jMenu9 = new javax.swing.JMenu();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("Abstraction Implementation Kit");
            setIconImages(null);
            setResizable(false);

            jPanel6.setLayout(null);

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menubar_package/2.PNG"))); // NOI18N
            jPanel6.add(jLabel1);
            jLabel1.setBounds(0, 0, 660, 530);

            jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jButton1.setText("Next");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menubar_package/2.PNG"))); // NOI18N

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jButton1)
                                    .addGap(64, 64, 64))
            );
            jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1)
                                    .addContainerGap())
            );

            jTabbedPane1.addTab("What is abstraction? ", jPanel2);

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGap(0, 719, Short.MAX_VALUE)
            );
            jPanel5Layout.setVerticalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGap(0, 574, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Implementation of Abstraction", jPanel5);

            jMenu1.setText("About");
            jMenu1.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
                public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                    jMenu1MenuKeyPressed(evt);
                }
                public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
                }
                public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
                }
            });

            jMenuItem1.setText("What is Abstraction?");
            jMenuItem1.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
                public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                    jMenuItem1MenuKeyPressed(evt);
                }
                public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
                }
                public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
                }
            });
            jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem1);

            jMenuItem9.setText("Implementation of Abstraction");
            jMenu1.add(jMenuItem9);

            jMenuBar1.add(jMenu1);

            jMenu5.setText("Stack");

            jMenu14.setText("What is a stack?");

            jMenuItem7.setText("Idea");
            jMenu14.add(jMenuItem7);

            jMenuItem17.setText("Inheritance diagram");
            jMenu14.add(jMenuItem17);

            jMenu5.add(jMenu14);

            jMenu12.setText("Creating a stack");

            jMenuItem10.setText("Algorithms");
            jMenu12.add(jMenuItem10);

            jMenuItem12.setText("Running the program");
            jMenu12.add(jMenuItem12);

            jMenu5.add(jMenu12);

            jMenu13.setText("Adding element in stack");

            jMenuItem13.setText("Algorithms");
            jMenu13.add(jMenuItem13);

            jMenuItem14.setText("Running the program");
            jMenu13.add(jMenuItem14);

            jMenu5.add(jMenu13);

            jMenu11.setText("Removing element from stack");

            jMenuItem15.setText("Algorithms");
            jMenu11.add(jMenuItem15);

            jMenuItem16.setText("Running the program");
            jMenu11.add(jMenuItem16);

            jMenu5.add(jMenu11);

            jMenu15.setText("Fetching elements from stack");

            jMenuItem8.setText("Algorithms");
            jMenu15.add(jMenuItem8);

            jMenuItem11.setText("Running the program");
            jMenu15.add(jMenuItem11);

            jMenu5.add(jMenu15);

            jMenuItem18.setText("Program code");
            jMenu5.add(jMenuItem18);

            jMenuBar1.add(jMenu5);

            jMenu6.setText("Circular Queue");

            jMenu16.setText("What is a circular queue?");

            jMenuItem19.setText("Idea");
            jMenu16.add(jMenuItem19);

            jMenuItem20.setText("Inheritance diagram");
            jMenu16.add(jMenuItem20);

            jMenu6.add(jMenu16);

            jMenu17.setText("Creating a circular queue");

            jMenuItem21.setText("Algorithms");
            jMenu17.add(jMenuItem21);

            jMenuItem22.setText("Running the program");
            jMenu17.add(jMenuItem22);

            jMenu6.add(jMenu17);

            jMenu18.setText("Adding element in circular queue");

            jMenuItem23.setText("Algorithms");
            jMenu18.add(jMenuItem23);

            jMenuItem24.setText("Running the program");
            jMenu18.add(jMenuItem24);

            jMenu6.add(jMenu18);

            jMenu19.setText("Removing element from circular queue");

            jMenuItem25.setText("Algorithms");
            jMenu19.add(jMenuItem25);

            jMenuItem26.setText("Running the program");
            jMenu19.add(jMenuItem26);

            jMenu6.add(jMenu19);

            jMenu20.setText("Fetching elements from circular queue");

            jMenuItem27.setText("Algorithms");
            jMenu20.add(jMenuItem27);

            jMenuItem28.setText("Running the program");
            jMenu20.add(jMenuItem28);

            jMenu6.add(jMenu20);

            jMenuItem29.setText("Program code");
            jMenu6.add(jMenuItem29);

            jMenuBar1.add(jMenu6);

            jMenu7.setText("Linear Queue");

            jMenu21.setText("What is a linear queue?");

            jMenuItem30.setText("Idea");
            jMenu21.add(jMenuItem30);

            jMenuItem31.setText("Inheritance diagram");
            jMenu21.add(jMenuItem31);

            jMenu7.add(jMenu21);

            jMenu22.setText("Creating a linear queue");

            jMenuItem32.setText("Algorithms");
            jMenu22.add(jMenuItem32);

            jMenuItem33.setText("Running the program");
            jMenu22.add(jMenuItem33);

            jMenu7.add(jMenu22);

            jMenu23.setText("Adding element in linear queue");

            jMenuItem34.setText("Algorithms");
            jMenu23.add(jMenuItem34);

            jMenuItem35.setText("Running the program");
            jMenu23.add(jMenuItem35);

            jMenu7.add(jMenu23);

            jMenu24.setText("Removing element from linear queue");

            jMenuItem36.setText("Algorithms");
            jMenu24.add(jMenuItem36);

            jMenuItem37.setText("Running the program");
            jMenu24.add(jMenuItem37);

            jMenu7.add(jMenu24);

            jMenu25.setText("Fetching elements from linear queue");

            jMenuItem38.setText("Algorithms");
            jMenu25.add(jMenuItem38);

            jMenuItem39.setText("Running the program");
            jMenu25.add(jMenuItem39);

            jMenu7.add(jMenu25);

            jMenuItem40.setText("Program code");
            jMenu7.add(jMenuItem40);

            jMenuBar1.add(jMenu7);

            jMenu8.setText("Linked List");
            jMenu8.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
                public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                    jMenu8MenuKeyPressed(evt);
                }
                public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
                }
                public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
                }
            });

            jMenu26.setText("What is a linked list?");

            jMenuItem41.setText("Idea");
            jMenu26.add(jMenuItem41);

            jMenuItem42.setText("Inheritance diagram");
            jMenu26.add(jMenuItem42);

            jMenu8.add(jMenu26);

            jMenu27.setText("Creating a linked list");

            jMenuItem43.setText("Algorithms");
            jMenu27.add(jMenuItem43);

            jMenuItem44.setText("Running the program");
            jMenu27.add(jMenuItem44);

            jMenu8.add(jMenu27);

            jMenu28.setText("Adding element in linked list");

            jMenuItem45.setText("Algorithms");
            jMenu28.add(jMenuItem45);

            jMenuItem46.setText("Running the program");
            jMenu28.add(jMenuItem46);

            jMenu8.add(jMenu28);

            jMenu29.setText("Removing element from linked list");

            jMenuItem47.setText("Algorithms");
            jMenu29.add(jMenuItem47);

            jMenuItem48.setText("Running the program");
            jMenu29.add(jMenuItem48);

            jMenu8.add(jMenu29);

            jMenu30.setText("Fetching elements from linked Llist");

            jMenuItem49.setText("Algorithms");
            jMenu30.add(jMenuItem49);

            jMenuItem50.setText("Running the program");
            jMenu30.add(jMenuItem50);

            jMenu8.add(jMenu30);

            jMenuItem51.setText("Program code");
            jMenu8.add(jMenuItem51);

            jMenuBar1.add(jMenu8);

            jMenu9.setText("Help");
            jMenuBar1.add(jMenu9);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1)
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1)
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>

        private void jMenu8MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            // TODO add your handling code here:
        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void jMenu1MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            // TODO add your handling code here:
        }

        private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void jMenuItem1MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            // TODO add your handling code here:
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Menubar().setVisible(true);
                }
            });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenu jMenu11;
        private javax.swing.JMenu jMenu12;
        private javax.swing.JMenu jMenu13;
        private javax.swing.JMenu jMenu14;
        private javax.swing.JMenu jMenu15;
        private javax.swing.JMenu jMenu16;
        private javax.swing.JMenu jMenu17;
        private javax.swing.JMenu jMenu18;
        private javax.swing.JMenu jMenu19;
        private javax.swing.JMenu jMenu20;
        private javax.swing.JMenu jMenu21;
        private javax.swing.JMenu jMenu22;
        private javax.swing.JMenu jMenu23;
        private javax.swing.JMenu jMenu24;
        private javax.swing.JMenu jMenu25;
        private javax.swing.JMenu jMenu26;
        private javax.swing.JMenu jMenu27;
        private javax.swing.JMenu jMenu28;
        private javax.swing.JMenu jMenu29;
        private javax.swing.JMenu jMenu30;
        private javax.swing.JMenu jMenu5;
        private javax.swing.JMenu jMenu6;
        private javax.swing.JMenu jMenu7;
        private javax.swing.JMenu jMenu8;
        private javax.swing.JMenu jMenu9;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuItem jMenuItem1;
        private javax.swing.JMenuItem jMenuItem10;
        private javax.swing.JMenuItem jMenuItem11;
        private javax.swing.JMenuItem jMenuItem12;
        private javax.swing.JMenuItem jMenuItem13;
        private javax.swing.JMenuItem jMenuItem14;
        private javax.swing.JMenuItem jMenuItem15;
        private javax.swing.JMenuItem jMenuItem16;
        private javax.swing.JMenuItem jMenuItem17;
        private javax.swing.JMenuItem jMenuItem18;
        private javax.swing.JMenuItem jMenuItem19;
        private javax.swing.JMenuItem jMenuItem20;
        private javax.swing.JMenuItem jMenuItem21;
        private javax.swing.JMenuItem jMenuItem22;
        private javax.swing.JMenuItem jMenuItem23;
        private javax.swing.JMenuItem jMenuItem24;
        private javax.swing.JMenuItem jMenuItem25;
        private javax.swing.JMenuItem jMenuItem26;
        private javax.swing.JMenuItem jMenuItem27;
        private javax.swing.JMenuItem jMenuItem28;
        private javax.swing.JMenuItem jMenuItem29;
        private javax.swing.JMenuItem jMenuItem30;
        private javax.swing.JMenuItem jMenuItem31;
        private javax.swing.JMenuItem jMenuItem32;
        private javax.swing.JMenuItem jMenuItem33;
        private javax.swing.JMenuItem jMenuItem34;
        private javax.swing.JMenuItem jMenuItem35;
        private javax.swing.JMenuItem jMenuItem36;
        private javax.swing.JMenuItem jMenuItem37;
        private javax.swing.JMenuItem jMenuItem38;
        private javax.swing.JMenuItem jMenuItem39;
        private javax.swing.JMenuItem jMenuItem40;
        private javax.swing.JMenuItem jMenuItem41;
        private javax.swing.JMenuItem jMenuItem42;
        private javax.swing.JMenuItem jMenuItem43;
        private javax.swing.JMenuItem jMenuItem44;
        private javax.swing.JMenuItem jMenuItem45;
        private javax.swing.JMenuItem jMenuItem46;
        private javax.swing.JMenuItem jMenuItem47;
        private javax.swing.JMenuItem jMenuItem48;
        private javax.swing.JMenuItem jMenuItem49;
        private javax.swing.JMenuItem jMenuItem50;
        private javax.swing.JMenuItem jMenuItem51;
        private javax.swing.JMenuItem jMenuItem7;
        private javax.swing.JMenuItem jMenuItem8;
        private javax.swing.JMenuItem jMenuItem9;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JTabbedPane jTabbedPane1;
        // End of variables declaration
    }



